/**
 * Injected styles for the dsh-history timeline panel.
 * Clean, flat list-table style strictly adhering to DSH Trajectory & DevTools aesthetics.
 * Left: CHECK POINT / USER+ASST message lines.
 * Right: Two-line stack (Top: TURN N + highlighted commit id code badge + HEAD; Bottom: relative time).
 */

export const STYLES = [
  '/* Floating Trigger Button (DSH capsule) */',
  '.dsh-history-trigger {',
  '  position: fixed;',
  '  right: 20px;',
  '  bottom: 20px;',
  '  z-index: 9999;',
  '  display: inline-flex;',
  '  align-items: center;',
  '  gap: 6px;',
  '  height: 36px;',
  '  padding: 0 14px;',
  '  background: var(--dsw-alias-button-tool-bar-fill, var(--dsw-alias-bg-layer-2, #2d2d2e));',
  '  color: var(--dsw-alias-label-primary, #e6e6e6);',
  '  border: none;',
  '  border-radius: 18px;',
  '  font-family: inherit;',
  '  font-size: 14px;',
  '  font-weight: 500;',
  '  cursor: pointer;',
  '  box-shadow: var(--dsw-shadow-lv3, 0 2px 10px rgba(0, 0, 0, 0.35));',
  '  transition: background 0.1s ease, color 0.1s ease;',
  '  user-select: none;',
  '}',
  '.dsh-history-trigger:hover {',
  '  background: var(--dsw-alias-button-tool-bar-hover, #3a3a3b);',
  '  color: #ffffff;',
  '}',
  '.dsh-history-trigger:active {',
  '  background: var(--dsw-alias-interactive-bg-active, rgba(255, 255, 255, 0.08));',
  '}',
  '/* Session-header HISTORY action (DSH header action row geometry). */',
  '.dsh-history-header-action {',
  '  min-height: 28px;',
  '  display: inline-flex;',
  '  align-items: center;',
  '  gap: 5px;',
  '  padding: 3px 8px;',
  '  border: 0;',
  '  border-radius: 6px;',
  '  background: transparent;',
  '  color: var(--dsw-alias-label-tertiary, #9a9aa0);',
  '  font-family: inherit;',
  '  font-size: 12px;',
  '  line-height: 18px;',
  '  font-weight: 500;',
  '  letter-spacing: 0.06em;',
  '  cursor: pointer;',
  '  user-select: none;',
  '  transform-origin: center;',
  '  transition: color 0.12s ease, transform 0.12s ease;',
  '}',
  '.dsh-history-header-action:hover,',
  '.dsh-history-header-action:focus-visible {',
  '  color: var(--dsw-alias-label-primary, #f5f5f7);',
  '  transform: scale(1.1);',
  '}',
  '.dsh-history-header-action svg {',
  '  flex: none;',
  '}',
  '.dsh-history-header-action:hover svg {',
  '  transform: none;',
  '}',
  /* Same style language for the shipped Session log button: borderless text
     button matching the HISTORY trigger (overrides dsh-session-log-export).
     Icon-first (row-reverse flips the DOM's text-then-icon order), uppercase. */
  '[class*="sessionLogButton"] {',
  '  min-height: 28px;',
  '  height: auto;',
  '  min-width: 0;',
  '  border: 0;',
  '  border-radius: 6px;',
  '  background: transparent !important;',
  '  color: var(--dsw-alias-label-tertiary, #9a9aa0);',
  '  padding: 3px 8px;',
  '  font-size: 12px;',
  '  line-height: 18px;',
  '  font-weight: 500;',
  '  letter-spacing: 0.06em;',
  '  gap: 5px;',
  '  flex-direction: row-reverse;',
  '  text-transform: uppercase;',
  '  transform-origin: center;',
  '  transition: color 0.12s ease, transform 0.12s ease;',
  '}',
  '[class*="sessionLogButton"]:hover:not(:disabled) {',
  '  background: transparent !important;',
  '  color: var(--dsw-alias-label-primary, #f5f5f7);',
  '  transform: scale(1.1);',
  '}',
  /* Modal Backdrop: spans the whole viewport purely to catch outside clicks.
     It carries NO blur and NO fill — the visual treatment lives in the blur
     layer below, which is confined to the conversation area. */
  '.dsh-history-modal-backdrop {',
  '  position: fixed;',
  '  inset: 0;',
  '  z-index: 10000;',
  '  background: transparent;',
  '  display: flex;',
  '  align-items: center;',
  '  justify-content: center;',
  '  padding: 24px 16px;',
  '  pointer-events: auto;',
  '  animation: dshFadeIn 0.2s ease-out;',
  '}',
  /* Blur layer: positioned over the conversation viewport only, so the sidebar
     and window chrome stay sharp. pointer-events:none so clicks pass through to
     the backdrop (click-outside-to-close keeps working across the whole app). */
  '.dsh-history-modal-blur {',
  '  position: fixed;',
  '  z-index: 0;',
  '  pointer-events: none;',
  /* No tint — blur only. The dark fill and the blur used to land at different
     times (the fill is a cheap paint, the blur needs a backdrop snapshot), which
     read as two separate stages. One effect cannot desync from itself. */
  '  backdrop-filter: blur(8px);',
  '  -webkit-backdrop-filter: blur(8px);',
  /* Progressive blur transition */
  '  backdrop-filter: blur(8px);',
  '  -webkit-backdrop-filter: blur(8px);',
  '  transition: backdrop-filter 0.5s cubic-bezier(0.16, 1, 0.3, 1), -webkit-backdrop-filter 0.5s cubic-bezier(0.16, 1, 0.3, 1), opacity 0.5s ease-out;',
  '  will-change: backdrop-filter, opacity;',
  '  animation: dshBlurIn 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards;',
  '}',
  '@keyframes dshBlurIn {',
  '  from {',
  '    backdrop-filter: blur(0px);',
  '    -webkit-backdrop-filter: blur(0px);',
  '    opacity: 0;',
  '  }',
  '  to {',
  '    backdrop-filter: blur(8px);',
  '    -webkit-backdrop-filter: blur(8px);',
  '    opacity: 1;',
  '  }',
  '}',
  '@keyframes dshFadeIn {',
  '  from { opacity: 0; }',
  '  to { opacity: 1; }',
  '}',
  '@keyframes dshSlideUp {',
  '  from { opacity: 0; transform: translateY(8px); }',
  '  to { opacity: 1; transform: translateY(0); }',
  '}',
  '.dsh-history-modal-card {',
  '  position: relative;',
  '  z-index: 1;', // above the blur layer (z-index 0)
  '  width: min(900px, 94vw);',
  '  height: 85vh;',
  '  max-height: 85vh;',
  '  display: flex;',
  '  flex-direction: column;',
  '  background: transparent !important;',
  '  border: none !important;',
  '  box-shadow: none !important;',
  '  overflow: visible;',
  '  color: var(--dsw-alias-label-primary, #e6e6e6);',
  '  font-family: inherit;',
  '}',
  '/* Header floating controls */',
  '.dsh-history-modal-head {',
  '  display: flex;',
  '  align-items: center;',
  '  justify-content: flex-end;',
  '  padding: 0 0 12px 0;',
  '  gap: 12px;',
  '}',
  '.dsh-history-modal-head-title {',
  '  display: flex;',
  '  align-items: center;',
  '  gap: 8px;',
  '  font-size: 16px;',
  '  line-height: 24px;',
  '  font-weight: 500;',
  '  color: var(--dsw-alias-label-primary, #f3f3f3);',
  '}',
  '.dsh-history-toolbar {',
  '  display: flex;',
  '  align-items: center;',
  '  justify-content: space-between;',
  '  padding: 6px 16px;',
  '  background: transparent;',
  '  gap: 12px;',
  '}',
  '.dsh-history-toolbar-stats {',
  '  display: flex;',
  '  align-items: center;',
  '  gap: 6px;',
  '  font-size: 12px;',
  '  color: var(--dsw-alias-label-secondary, #888888);',
  '}',
  '/* Panel & Timeline Floating Cards Body */',
  '.dsh-history-panel {',
  '  display: flex;',
  '  flex-direction: column;',
  '  flex: 1 1 auto;',
  '  height: 100%;',
  '  max-height: 100%;',
  '  min-height: 0;',
  '  position: relative;',
  '  background: transparent !important;',
  '}',
  '.dsh-history-modal-body {',
  '  flex: 1;',
  '  min-height: 0;',
  '  overflow-y: auto;',
  '  overflow-x: hidden;',
  '  padding: 12px 10px 40px 10px;',
  '  display: flex;',
  '  flex-direction: column;',
  /* Edge fade: the scrollport has no frame, so a hard clip at its boundary
     reads as a rendering bug. Dissolve the first and last 28px instead, so
     cards fade out of view rather than being cut off. */
  '  -webkit-mask-image: linear-gradient(to bottom, transparent 0, #000 28px, #000 calc(100% - 28px), transparent 100%);',
  '  mask-image: linear-gradient(to bottom, transparent 0, #000 28px, #000 calc(100% - 28px), transparent 100%);',
  '}',
  /* Centering that stays scrollable: margin auto centers when content is
     shorter than the viewport, but collapses to 0 when it overflows, so the
     top cards stay reachable by scrolling. */
  '.dsh-history-modal-body > :first-child {',
  '  margin-top: auto;',
  '}',
  '.dsh-history-modal-body > :last-child {',
  '  margin-bottom: auto;',
  '}',
  /* Scrollbar: hidden at rest, revealed while scrolling (.is-scrolling, set for
     a moment by the scroll handler) and on hover. The track keeps its width at
     all times so revealing the thumb never reflows the cards. */
  '.dsh-history-modal-body::-webkit-scrollbar {',
  '  width: 6px;',
  '}',
  '.dsh-history-modal-body::-webkit-scrollbar-track {',
  '  background: transparent;',
  '}',
  '.dsh-history-modal-body::-webkit-scrollbar-thumb {',
  '  background: transparent;',
  '  border-radius: 3px;',
  '}',
  /* Revealed only while genuinely scrolling (.is-scrolling) or while the pointer
     is in the narrow strip along the right edge (.is-near-bar). Hovering the
     cards themselves must NOT reveal it. */
  '.dsh-history-modal-body.is-scrolling::-webkit-scrollbar-thumb,',
  '.dsh-history-modal-body.is-near-bar::-webkit-scrollbar-thumb {',
  '  background: rgba(255, 255, 255, 0.15);',
  '}',
  '.dsh-history-modal-body.is-scrolling::-webkit-scrollbar-thumb:hover,',
  '.dsh-history-modal-body.is-near-bar::-webkit-scrollbar-thumb:hover {',
  '  background: rgba(255, 255, 255, 0.28);',
  '}',
  '/* Firefox: no pseudo-element control, so use the standard properties. */',
  '.dsh-history-modal-body {',
  '  scrollbar-width: thin;',
  '  scrollbar-color: transparent transparent;',
  '}',
  '.dsh-history-modal-body.is-scrolling,',
  '.dsh-history-modal-body.is-near-bar {',
  '  scrollbar-color: rgba(255, 255, 255, 0.22) transparent;',
  '}',
  '/* Floating Timeline Row & Card Styling */',
  '.dsh-history-row {',
  '  display: flex;',
  '  align-items: stretch;',
  '  gap: 12px;',
  '  cursor: pointer;',
  '  padding: 0;',
  '  margin: 0;',
  '  border: none;',
  '  position: relative;',
  '  background: transparent !important;',
  '}',
  /* Graph column: ONE continuous SVG for the whole list, absolutely
     positioned over the rows. Rails are single unbroken paths from a child
     node centre to its parent node centre, so there are no per-row segment
     joins and therefore no visible seams. */
  '.dsh-history-list {',
  '  position: relative;',
  '  display: flex;',
  '  flex-direction: column;',
  '}',
  '.dsh-history-graph-overlay {',
  '  position: absolute;',
  '  top: 0;',
  '  left: 0;',
  '  pointer-events: none;',
  '  overflow: visible;',
  '  background: transparent;',
  '  filter: drop-shadow(0 2px 6px rgba(0, 0, 0, 0.4));',
  '}',
  '/* Reserved gutter each row leaves for the graph overlay. */',
  '.dsh-history-gutter {',
  '  flex: none;',
  '  align-self: stretch;',
  '}',
  '.dsh-history-node {',
  '  transition: r 0.12s ease;',
  '}',
  '/* Floating Card Component */',
  '.dsh-history-row-content {',
  '  display: flex;',
  /* Bottom-align the two flex children (main content + side time/sha column)
     instead of vertically centering them. Multi-line TURN cards (USER + ASST
     + file chips) are taller than the single-line side column; centering put
     the time/sha badge in the visual middle of the card instead of pinned to
     its last line. Bottom-aligning keeps the side column level with whichever
     line the card ends on, for 1-line and multi-line cards alike. */
  '  align-items: flex-end;',
  '  justify-content: space-between;',
  '  min-width: 0;',
  '  flex: 1;',
  '  gap: 14px;',
  /* Vertical padding, not a fixed height: the card grows with however many
     text lines it carries (1-line WORKSPACE, 2-line TURN, 3-line TURN+files). */
  '  padding: 10px 16px;',
  '  margin: 4px 0;',
  /* Opaque-ish fill, NOT backdrop-filter. Each card having its own
     backdrop-filter meant ~40 separate compositing layers on open (one per
     rendered row), each snapshotting its own backdrop. The cheap single
     background layer finished first and the cards' glass caught up over the
     following frames — that lag was the "opens out of sync" artifact. The cards
     already float over an ALREADY-blurred backdrop, so blurring again bought
     almost nothing visually while costing the whole opening frame budget. */
  '  background: var(--dsw-alias-bg-layer-2, rgba(38, 38, 42, 0.94));',
  '  border: 1px solid var(--dsw-alias-border-inverted, rgba(255, 255, 255, 0.12));',
  '  border-radius: 14px;',
  '  box-shadow: 0 4px 16px rgba(0, 0, 0, 0.35);',
  '  transition: transform 0.15s ease, border-color 0.15s ease, background 0.15s ease, box-shadow 0.15s ease;',
  '}',
  /* Hover/selected fills are re-balanced for the now-opaque base: the old 0.95
     hover was indistinguishable from a 0.94 base, and the old 0.18 blue relied
     on a blur behind it to read as a tint. */
  '.dsh-history-row:hover .dsh-history-row-content {',
  '  background: var(--dsw-alias-bg-layer-3, rgba(58, 58, 64, 0.97));',
  '  border-color: rgba(255, 255, 255, 0.25);',
  '  transform: translateY(-1px);',
  '  box-shadow: 0 6px 20px rgba(0, 0, 0, 0.5);',
  '}',
  '.dsh-history-row.is-selected .dsh-history-row-content {',
  '  background: rgba(46, 66, 112, 0.96) !important;',
  '  border-color: rgba(77, 136, 255, 0.6) !important;',
  '  box-shadow: 0 0 16px rgba(77, 136, 255, 0.35);',
  '}',
  '.dsh-history-row-main {',
  '  display: flex;',
  '  flex-direction: column;',
  '  justify-content: center;',
  '  min-width: 0;',
  '  flex: 1;',
  '  gap: 4px;',
  '}',
  '/* Badges */',
  '.dsh-badge {',
  '  display: inline-flex;',
  '  align-items: center;',
  '  padding: 0 4px;',
  '  border-radius: 2px;',
  '  font-size: 10px;',
  '  font-family: var(--ds-font-family-code, monospace);',
  '  font-weight: 600;',
  '  line-height: 14px;',
  '  letter-spacing: 0.02em;',
  '}',
  '.dsh-badge-head {',
  '  background: #2563eb;',
  '  color: #ffffff;',
  '}',
  '.dsh-badge-turn {',
  '  background: rgba(255, 255, 255, 0.08);',
  '  color: var(--dsw-alias-label-secondary, #bbbbbb);',
  '  font-weight: 600;',
  '}',
  '.dsh-badge-turn-start {',
  '  background: rgba(16, 185, 129, 0.15);',
  '  color: #34d399;',
  '  font-size: 10px;',
  '  line-height: 14px;',
  '}',
  '.dsh-badge-turn-end {',
  '  background: rgba(77, 136, 255, 0.15);',
  '  color: #70a1ff;',
  '}',
  '.dsh-badge-manual {',
  '  background: rgba(245, 158, 11, 0.15);',
  '  color: #fbbf24;',
  '}',
  '.dsh-badge-rewind {',
  '  background: rgba(236, 72, 153, 0.15);',
  '  color: #f472b6;',
  '}',
  '/* Commit SHA Highlight Badge */',
  '.dsh-history-sha-badge {',
  '  font-family: var(--ds-font-family-code, monospace);',
  '  font-size: 10px;',
  '  line-height: 14px;',
  '  color: var(--dsw-alias-label-primary, #e2e8f0);',
  '  background: var(--dsw-alias-bg-layer-2, rgba(255, 255, 255, 0.08));',
  '  border: 1px solid var(--dsw-alias-border-l1, rgba(255, 255, 255, 0.12));',
  '  padding: 0 4px;',
  '  border-radius: 3px;',
  '  letter-spacing: 0.02em;',
  '}',
  '/* Message lines */',
  '.dsh-history-msg-list {',
  '  display: flex;',
  '  flex-direction: column;',
  '  gap: 2px;',
  '  min-width: 0;',
  '}',
  '.dsh-history-msg-item {',
  '  display: flex;',
  '  align-items: center;',
  '  gap: 6px;',
  '  min-width: 0;',
  '}',
  '.dsh-history-msg-role {',
  '  flex: none;',
  '  font: 600 10px/14px var(--ds-font-family-code, monospace);',
  '  padding: 0 4px;',
  '  border-radius: 2px;',
  '  letter-spacing: 0.02em;',
  '}',
  '.dsh-history-msg-role-user {',
  '  color: #70a1ff;',
  '  background: rgba(77, 136, 255, 0.15);',
  '}',
  '.dsh-history-msg-role-asst {',
  '  color: #c084fc;',
  '  background: rgba(192, 132, 252, 0.15);',
  '}',
  '.dsh-history-msg-text {',
  '  min-width: 0;',
  '  overflow: hidden;',
  '  text-overflow: ellipsis;',
  '  white-space: nowrap;',
  '  color: var(--dsw-alias-label-primary, #dddddd);',
  '  font: 11.5px/16px var(--ds-font-family-code, monospace);',
  '}',
  '/* Single-line checkpoint / manual text */',
  '.dsh-history-single-line {',
  '  display: flex;',
  '  align-items: center;',
  '  flex-wrap: wrap;',
  '  gap: 6px;',
  '  min-width: 0;',
  '}',
  '.dsh-history-single-text {',
  '  color: var(--dsw-alias-label-secondary, #999999);',
  '  font: 11.5px/16px var(--ds-font-family-code, monospace);',
  '  overflow: hidden;',
  '  text-overflow: ellipsis;',
  '  white-space: nowrap;',
  '}',
  '/* Changed-file chips on CHECK POINT / TURN rows: one highlighted block per file. */',
  '.dsh-history-file-list {',
  '  display: flex;',
  '  flex-wrap: nowrap;',
  '  align-items: center;',
  '  gap: 4px;',
  '  min-width: 0;',
  '}',
  /* Changed-file chip: white fill, black text — reads as a highlighter mark
     against the translucent card. */
  '.dsh-history-file-chip {',
  '  flex: none;',
  '  display: inline-flex;',
  '  align-items: center;',
  '  padding: 0 7px;',
  '  border-radius: 3px;',
  '  font-size: 10px;',
  '  font-family: var(--ds-font-family-code, monospace);',
  '  font-weight: 600;',
  '  line-height: 15px;',
  '  letter-spacing: 0.02em;',
  '  color: #14141a;',
  '  background: #c8c8ce;',
  '  white-space: nowrap;',
  '}',
  '/* Overflow indicator ("+N"): same mark, dimmed so it reads as a count. */',
  '.dsh-history-file-chip.is-more {',
  '  color: #2e2e36;',
  '  background: rgba(200, 200, 206, 0.58);',
  '}',
  '/* TURN rows: the changed-file line indents to the message TEXT column so it',
  '   aligns with the USER/ASST content (not with the role badges). The spacer',
  '   reuses the badge font so 4ch measures exactly the USER/ASST label width,',
  '   plus the badge padding (2x4px) and the 6px item gap. */',
  '.dsh-history-file-indent {',
  '  flex: none;',
  '  width: calc(4ch + 14px);',
  '  font: 600 10px/14px var(--ds-font-family-code, monospace);',
  '}',
  /* Chip line: the visible count is computed to fit the measured width, so
     chips normally render at full length and never shrink. overflow:hidden and
     the shrink rule below only act as a safety net for the pathological case of
     a single file name wider than the whole row. */
  '.dsh-history-file-clip {',
  '  display: flex;',
  '  flex-wrap: nowrap;',
  '  align-items: center;',
  '  gap: 4px;',
  '  overflow: hidden;',
  '  min-width: 0;',
  '  flex: 1;',
  '}',
  '.dsh-history-file-clip .dsh-history-file-chip {',
  '  flex: 0 1 auto;',
  '  min-width: 0;',
  '  overflow: hidden;',
  '  text-overflow: ellipsis;',
  '}',
  '/* Right Side Meta Info: `` id badge + relative time, one right-aligned line */',
  '.dsh-history-row-side {',
  '  display: flex;',
  '  align-items: center;',
  '  justify-content: flex-end;',
  '  flex: none;',
  '  gap: 6px;',
  '}',
  '.dsh-history-time {',
  '  color: var(--dsw-alias-label-secondary, #737373);',
  '  font-size: 9.5px;',
  '  line-height: 12px;',
  '  opacity: 0.85;',
  '}',
  '/* Buttons: DSH capsule geometry (figma Button 1:155 — r18, h36, pad 14). */',
  '.dsh-history-button {',
  '  display: inline-flex;',
  '  align-items: center;',
  '  justify-content: center;',
  '  gap: 4px;',
  '  border: none;',
  '  border-radius: 18px;',
  '  height: 36px;',
  '  padding: 0 14px;',
  '  font-family: inherit;',
  '  font-size: 14px;',
  '  line-height: 22px;',
  '  color: var(--dsw-alias-label-primary, #e6e6e6);',
  '  background: transparent;',
  '  cursor: pointer;',
  '  transition: background 0.1s ease, color 0.1s ease;',
  '  user-select: none;',
  '}',
  '.dsh-history-button:hover:not(:disabled) {',
  '  background: var(--dsw-alias-interactive-bg-hover, rgba(255, 255, 255, 0.06));',
  '}',
  '.dsh-history-button:active:not(:disabled) {',
  '  background: var(--dsw-alias-interactive-bg-active, rgba(255, 255, 255, 0.08));',
  '}',
  '.dsh-history-button:disabled {',
  '  cursor: not-allowed;',
  '  opacity: 0.4;',
  '}',
  /* Primary: solid brand capsule — distinctly filled vs. outline siblings. */
  '.dsh-history-button.primary {',
  '  background: #2563eb;',
  '  color: #ffffff;',
  '  border: 1px solid rgba(255, 255, 255, 0.16);',
  '  box-shadow: 0 4px 14px rgba(37, 99, 235, 0.35);',
  '}',
  '.dsh-history-button.primary:hover:not(:disabled) {',
  '  background: #3b82f6;',
  '  border-color: rgba(255, 255, 255, 0.28);',
  '  box-shadow: 0 6px 18px rgba(37, 99, 235, 0.5);',
  '}',
  /* Outline: bordered capsule on transparent fill (figma Dialog Cancel). */
  '.dsh-history-button.outline {',
  '  border: 1px solid var(--dsw-alias-border-l2, rgba(255, 255, 255, 0.2));',
  '  background: var(--dsw-alias-button-tool-bar-fill, rgba(255, 255, 255, 0.08));',
  '  color: var(--dsw-alias-label-primary, #e6e6e6);',
  '  transition: background 0.15s ease, border-color 0.15s ease, color 0.15s ease, box-shadow 0.15s ease;',
  '}',
  '.dsh-history-button.outline:hover:not(:disabled) {',
  '  background: var(--dsw-alias-button-tool-bar-hover, rgba(255, 255, 255, 0.18));',
  '  border-color: rgba(255, 255, 255, 0.38);',
  '  color: #ffffff;',
  '  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.3);',
  '}',
  '.dsh-history-button.outline:active:not(:disabled) {',
  '  background: var(--dsw-alias-interactive-bg-active, rgba(255, 255, 255, 0.22));',
  '  border-color: rgba(255, 255, 255, 0.45);',
  '}',
  /* Small (delete / compact toolbar remnants). */
  '.dsh-history-button.sm {',
  '  height: 28px;',
  '  font-size: 12px;',
  '  line-height: 18px;',
  '  padding: 0 10px;',
  '  border-radius: 14px;',
  '}',
  '/* Bottom Dock / Rewind Action Strip */',
  '.dsh-history-action-dock {',
  '  background: var(--dsw-alias-bg-layer-1, #232324);',
  '  border-top: 1px solid var(--dsw-alias-border-l2, rgba(255, 255, 255, 0.12));',
  '  padding: 8px 14px;',
  '  display: flex;',
  '  align-items: center;',
  '  justify-content: space-between;',
  '  gap: 12px;',
  '  animation: dshFadeIn 0.1s ease-out;',
  '}',
  '.dsh-history-action-info {',
  '  display: flex;',
  '  align-items: center;',
  '  gap: 12px;',
  '  min-width: 0;',
  '  flex: 1;',
  '}',
  '.dsh-history-action-title {',
  '  font-size: 12px;',
  '  font-weight: 600;',
  '  color: var(--dsw-alias-label-primary, #ffffff);',
  '  white-space: nowrap;',
  '}',
  '.dsh-history-check {',
  '  display: inline-flex;',
  '  align-items: center;',
  '  gap: 5px;',
  '  cursor: pointer;',
  '  color: var(--dsw-alias-label-primary, #cccccc);',
  '  font-size: 11.5px;',
  '  user-select: none;',
  '  white-space: nowrap;',
  '}',
  '.dsh-history-check input[type="checkbox"] {',
  '  cursor: pointer;',
  '  accent-color: var(--dsw-alias-brand-primary, #4d88ff);',
  '  margin: 0;',
  '}',
  '.dsh-history-actions {',
  '  display: flex;',
  '  gap: 6px;',
  '  align-items: center;',
  '  flex: none;',
  '}',
  '/* Modal Footer */',
  '.dsh-history-modal-foot {',
  '  display: flex;',
  '  align-items: center;',
  '  justify-content: space-between;',
  '  padding: 6px 14px;',
  '  background: var(--dsw-specific-sidebar-fill, #181818);',
  '  border-top: 1px solid var(--dsw-alias-border-l1, rgba(255, 255, 255, 0.08));',
  '  font-size: 11px;',
  '}',
  '.dsh-history-hint {',
  '  color: var(--dsw-alias-label-secondary, #888888);',
  '  font-size: 11px;',
  '  line-height: 1.4;',
  '  white-space: pre-wrap;',
  '}',
  '/* Dialog (figma 451:18655): r24, shadow-lv3, layer-2 fill, inverted border. */',
  '.dsh-history-dialog {',
  '  display: flex;',
  '  flex-direction: column;',
  '  gap: 20px;',
  '  width: min(400px, 100%);',
  '  padding: 0 0 24px;',
  '  overflow: hidden;',
  '  border: 1px solid var(--dsw-alias-border-inverted, rgba(255, 255, 255, 0.18));',
  '  border-radius: 24px;',
  '  background: var(--dsw-alias-bg-layer-2, #252526);',
  '  box-shadow: var(--dsw-shadow-lv3, 0 8px 24px rgba(0, 0, 0, 0.5));',
  '}',
  '.dsh-history-dialog-head {',
  '  display: flex;',
  '  align-items: center;',
  '  justify-content: space-between;',
  '  gap: 8px;',
  '  padding: 22px 14px 0 24px;',
  '}',
  '.dsh-history-dialog-title {',
  '  margin: 0;',
  '  font-size: 16px;',
  '  line-height: 24px;',
  '  font-weight: 500;',
  '  color: var(--dsw-alias-label-primary, #f3f3f3);',
  '}',
  '.dsh-history-dialog-close {',
  '  flex: none;',
  '  display: inline-flex;',
  '  align-items: center;',
  '  justify-content: center;',
  '  width: 28px;',
  '  height: 28px;',
  '  border: none;',
  '  border-radius: 8px;',
  '  background: transparent;',
  '  cursor: pointer;',
  '  color: var(--dsw-alias-label-secondary, #999999);',
  '  transform-origin: center;',
  '  transition: color 0.12s ease, transform 0.12s ease, background 0.12s ease;',
  '}',
  '.dsh-history-dialog-close:hover {',
  '  background: var(--dsw-alias-interactive-bg-hover, rgba(255, 255, 255, 0.1));',
  '  color: var(--dsw-alias-label-primary, #f5f5f7);',
  '  transform: scale(1.1);',
  '}',
  '.dsh-history-dialog-body {',
  '  display: flex;',
  '  flex-direction: column;',
  '  gap: 8px;',
  '  padding: 0 24px;',
  '}',
  '.dsh-history-dialog-description {',
  '  margin: 0;',
  '  padding: 0 24px;',
  '  font-size: 14px;',
  '  line-height: 22px;',
  '  color: var(--dsw-alias-label-primary, #e6e6e6);',
  '}',
  '.dsh-history-dialog-foot {',
  '  display: flex;',
  '  align-items: center;',
  '  justify-content: flex-end;',
  '  gap: 8px;',
  '  padding: 0 24px;',
  '}',
  '.dsh-history-input {',
  '  background: var(--dsw-alias-bg-base, #1e1e1e);',
  '  color: var(--dsw-alias-label-primary, #e6e6e6);',
  '  border: 1px solid var(--dsw-alias-border-l1, rgba(255, 255, 255, 0.15));',
  '  border-radius: 3px;',
  '  padding: 3px 6px;',
  '  font-size: 11px;',
  '  font-family: var(--ds-font-family-code, monospace);',
  '  width: 100%;',
  '  box-sizing: border-box;',
  '  outline: none;',
  '}',
  '.dsh-history-input:focus {',
  '  border-color: var(--dsw-alias-brand-primary, #4d88ff);',
  '}',
  '.dsh-history-label {',
  '  color: var(--dsw-alias-label-secondary, #999999);',
  '  font-size: 11px;',
  '}',
  /* Rewind progress: blur mask with smooth fade transition */
  '.dsh-history-progress-mask {',
  '  position: fixed;',
  '  inset: 0;',
  '  z-index: 10001;',
  '  background: rgba(0, 0, 0, 0.45);',
  '  backdrop-filter: blur(8px);',
  '  -webkit-backdrop-filter: blur(8px);',
  '  opacity: 1;',
  '  animation: dshMaskFadeIn 0.2s ease-out;',
  '  transition: opacity 0.4s cubic-bezier(0.16, 1, 0.3, 1), backdrop-filter 0.4s cubic-bezier(0.16, 1, 0.3, 1);',
  '}',
  '@keyframes dshMaskFadeIn {',
  '  from { opacity: 0; }',
  '  to { opacity: 1; }',
  '}',
  '/* Rewind progress card: centered DSH-style status card, spinner + text */',
  '.dsh-history-progress-card {',
  '  position: fixed;',
  '  top: 50%;',
  '  left: 50%;',
  '  transform: translate(-50%, -50%) scale(1);',
  '  z-index: 10002;',
  '  display: flex;',
  '  align-items: center;',
  '  gap: 16px;',
  '  min-width: 260px;',
  '  max-width: 400px;',
  '  padding: 22px 28px;',
  '  border-radius: 20px;',
  '  background: var(--dsw-alias-bg-layer-2, #252526);',
  '  border: 1px solid var(--dsw-alias-border-inverted, rgba(255, 255, 255, 0.18));',
  '  box-shadow: var(--dsw-shadow-lv3, 0 16px 48px rgba(0, 0, 0, 0.55));',
  '  opacity: 1;',
  '  animation: dshCardPopIn 0.25s cubic-bezier(0.16, 1, 0.3, 1);',
  '  transition: opacity 0.35s cubic-bezier(0.16, 1, 0.3, 1), transform 0.35s cubic-bezier(0.16, 1, 0.3, 1);',
  '}',
  '@keyframes dshCardPopIn {',
  '  from {',
  '    opacity: 0;',
  '    transform: translate(-50%, -46%) scale(0.96);',
  '  }',
  '  to {',
  '    opacity: 1;',
  '    transform: translate(-50%, -50%) scale(1);',
  '  }',
  '}',
  '.dsh-history-progress-spin {',
  '  width: 22px;',
  '  height: 22px;',
  '  flex: none;',
  '  border-radius: 50%;',
  '  border: 2.5px solid var(--dsw-alias-border-l2, rgba(255, 255, 255, 0.18));',
  '  border-top-color: var(--dsw-alias-brand-primary, #4d88ff);',
  '  animation: dshHistorySpin 0.85s linear infinite;',
  '}',
  '@keyframes dshHistorySpin {',
  '  to { transform: rotate(360deg); }',
  '}',
  '.dsh-history-progress-done {',
  '  width: 22px;',
  '  height: 22px;',
  '  flex: none;',
  '  display: inline-flex;',
  '  align-items: center;',
  '  justify-content: center;',
  '  border-radius: 50%;',
  '  background: var(--dsw-alias-state-success-primary, #34d399);',
  '  color: #0a0a0a;',
  '  font-size: 13px;',
  '  font-weight: 700;',
  '}',
  '.dsh-history-progress-text {',
  '  display: flex;',
  '  flex-direction: column;',
  '  gap: 5px;',
  '}',
  '.dsh-history-progress-title {',
  '  color: var(--dsw-alias-label-primary, #e6e6e6);',
  '  font-size: 14px;',
  '  font-weight: 600;',
  '  line-height: 1.2;',
  '}',
  '.dsh-history-progress-sha {',
  '  font-family: var(--ds-font-family-code, monospace);',
  '  font-size: 12px;',
  '  color: var(--dsw-alias-label-secondary, #999999);',
  '}',
].join('\n')

const STYLE_ELEMENT_ID = 'dsh-history-styles'

export function injectStyles(): void {
  const existing = document.getElementById(STYLE_ELEMENT_ID)
  if (existing !== null) {
    existing.textContent = STYLES
    return
  }
  const style = document.createElement('style')
  style.id = STYLE_ELEMENT_ID
  style.textContent = STYLES
  document.head.appendChild(style)
}

export const TRIGGER = 'dsh-history-trigger'
export const PANEL = 'dsh-history-panel'
export const TOOLBAR = 'dsh-history-toolbar'
export const ROW = 'dsh-history-row'
export const ROW_CONTENT = 'dsh-history-row-content'
export const ROW_MAIN = 'dsh-history-row-main'
export const ROW_SIDE = 'dsh-history-row-side'
export const SHA_BADGE = 'dsh-history-sha-badge'
export const MSG_LIST = 'dsh-history-msg-list'
export const MSG_ITEM = 'dsh-history-msg-item'
export const MSG_ROLE = 'dsh-history-msg-role'
export const MSG_ROLE_USER = 'dsh-history-msg-role-user'
export const MSG_ROLE_ASST = 'dsh-history-msg-role-asst'
export const MSG_TEXT = 'dsh-history-msg-text'
export const SINGLE_LINE = 'dsh-history-single-line'
export const SINGLE_TEXT = 'dsh-history-single-text'
export const FILE_LIST = 'dsh-history-file-list'
export const FILE_CHIP = 'dsh-history-file-chip'
export const FILE_CLIP = 'dsh-history-file-clip'
export const FILE_INDENT = 'dsh-history-file-indent'
export const BUTTON = 'dsh-history-button'
export const ACTION_DOCK = 'dsh-history-action-dock'
export const ACTION_INFO = 'dsh-history-action-info'
export const ACTION_TITLE = 'dsh-history-action-title'
export const DIALOG = 'dsh-history-dialog'
export const DIALOG_HEAD = 'dsh-history-dialog-head'
export const DIALOG_TITLE = 'dsh-history-dialog-title'
export const DIALOG_CLOSE = 'dsh-history-dialog-close'
export const DIALOG_BODY = 'dsh-history-dialog-body'
export const DIALOG_DESCRIPTION = 'dsh-history-dialog-description'
export const DIALOG_FOOT = 'dsh-history-dialog-foot'
export const CHECK = 'dsh-history-check'
export const ACTIONS = 'dsh-history-actions'
export const HINT = 'dsh-history-hint'
export const INPUT = 'dsh-history-input'
export const LABEL = 'dsh-history-label'
export const MODAL_BACKDROP = 'dsh-history-modal-backdrop'
export const MODAL_BLUR = 'dsh-history-modal-blur'
export const MODAL_CARD = 'dsh-history-modal-card'
export const MODAL_HEAD = 'dsh-history-modal-head'
export const MODAL_BODY = 'dsh-history-modal-body'
export const MODAL_FOOT = 'dsh-history-modal-foot'
export const GRAPH_OVERLAY = 'dsh-history-graph-overlay'
export const GRAPH_GUTTER = 'dsh-history-gutter'
export const LIST_WRAP = 'dsh-history-list'
export const PROGRESS_MASK = 'dsh-history-progress-mask'
export const PROGRESS_CARD = 'dsh-history-progress-card'
